function AssemblePlots

% August 20, 2014 (Rostock)
% 
% Assemble files generated by NumberOfTextonsV2.m into a single plot

load TextonNumG1B1V1
AllNT = NTvec';
AllWD = WCDmat';

load TextonNumG1B1V2
AllNT = [AllNT ; NTvec'];
AllWD = [AllWD ; WCDmat'];

load TextonNumG1B1V3
AllNT = [AllNT ; NTvec'];
AllWD = [AllWD ; WCDmat'];

load TextonNumG1B1V4
AllNT = [AllNT ; NTvec'];
AllWD = [AllWD ; WCDmat'];

load TextonNumG1B1V5
AllNT = [AllNT ; NTvec'];
AllWD = [AllWD ; WCDmat'];

load TextonNumG1B1V6
AllNT = [AllNT ; NTvec'];
AllWD = [AllWD ; WCDmat'];  

[SF,SI] = sort(AllNT);
WD = AllWD(SI,:)

TruD = log(WD(:,1));
RanD = log(WD(:,2));

figure(1)
plot(SF,TruD,'b','linewidt',2)
hold on
plot(SF,RanD,'r','linewidt',2)
hold off

figure(2)
DiffD = RanD - TruD;
plot(SF,DiffD,'linewidth',2)
set(gca,'xtick',[1, 551, 1500, 3000, 6000],'fontsize',18)
xlabel('Number of clusters','fontsize',18)
ylabel('Difference of within cluster disntances','fontsize',18)

figure(3)
L = length(DiffD);
Xvec = SF(L-2:L);
Yvec = DiffD(L-2:L);
p = polyfit(Xvec,Yvec,2);
hold on
xc = -p(2)/(2*p(1));
xc = round(xc);
fitx = linspace(1500,6000,400);
yfit = polyval(p,fitx);
disp(['vertex of quadratic fit is at ' int2str(xc)])
plot(SF,DiffD,'linewidth',2)
hold on
plot(fitx,yfit,'r','linewidth',2)
set(gca,'xtick',[1, 551, 1500, 3000, 6000],'fontsize',18)
xlabel('Number of clusters','fontsize',18)
ylabel('Difference of within cluster disntances','fontsize',18)

