function Draw2DexampleStage2(drawx,drawy)

% September 17 2014 (Rostock)
%
% This program uses input arrays drawx and drawy generated by
% Draw2example.m to draw an irregular figure in the plane. The initial
% intention was that Draw2example.m be used to draw the figure, but it was
% decided that using one program to generate the 'control points' and
% another to draw the figure would be easier. The arrays drawx and drawy
% are stored in a file called controlpoints.mat

[n,m20] = size(drawx);

m = 100;  % number of interpolation points between control points.
xvec = zeros(1,n*m);
yvec = zeros(1,n*m);

for k = 1:n
    cxvec = drawx(k,:);
    cyvec = drawy(k,:);
    nz1vec = find(abs(cxvec) > 0);
    nz2vec = find(abs(cyvec) > 0);
    nz1 = length(nz1vec);
    nz2 = length(nz2vec);
    nz = max(nz1,nz2);
    cxvec = cxvec(1:nz);
    cyvec = cyvec(1:nz);
    t = 1:nz;
    tt = linspace(1,nz,m);
    xx = spline(t,cxvec,tt);
    yy = spline(t,cyvec,tt);
    a = m*(k-1) + 1;
    b = m*k;
    xvec(a:b) = xx';
    yvec(a:b) = yy';
end

subplot('position',[0 0 1 1])
xvec = [xvec xvec(1)];
yvec = [yvec yvec(1)];
C = rgb('lightsteelblue');
patch(xvec,yvec,C)
hold on


% draw the oriented thicknesses
p = 0.1;
q = -0.06;
plot(p,q,'om','linewidth',2)
v1 = .49;
plot([p;p],[q;v1],'m','linewidth',2)
v5 = 0.635;
plot([p;p],[q;-v5],'m','linewidth',2)
v3 = .44;
plot([p;v3],[q;q],'m','linewidth',2)
v7 = .82;
plot([p;-v7],[q;q],'m','linewidth',2)
t2 = 1;
v2 = sqrt(2)*t2;
plot([p;p+t2],[q;q+t2],'m','linewidth',2)
t4 = 1;
v4 = sqrt(2)*t4;
plot([p;p+t4],[q;q-t4],'m','linewidth',2)
t8 = .587;
v8 = sqrt(2)*t8;
plot([p;p-t8],[q;q+t8],'m','linewidth',2)
t6 = 1;
v6 = sqrt(2)*t6;
plot([p;p-t6],[q;q-t6],'m','linewidth',2)

p = -0.7;
q = 0.1;
plot(p,q,'ob','linewidth',2)
v1 = 0.025;
plot([p;p],[q;q+v1],'b','linewidth',2)
v5 = 0.252;
plot([p;p],[q;q-v5],'b','linewidth',2)
v3 = 0.13;
plot([p;p+v3],[q;q],'b','linewidth',2)
v7 = .065;
plot([p;p-v7],[q;q],'b','linewidth',2)
t2 = 0.027;
v2 = sqrt(2)*t2;
plot([p;p+t2],[q;q+t2],'b','linewidth',2)
t4 = 0.745;
v4 = sqrt(2)*t4;
plot([p;p+t4],[q;q-t4],'b','linewidth',2)
t8 = 0.025;
v8 = sqrt(2)*t8;
plot([p;p-t8],[q;q+t8],'b','linewidth',2)
t6 = 0.12;
v6 = sqrt(2)*t6;
plot([p;p-t6],[q;q-t6],'b','linewidth',2)



axis([-1 1 -1 1])
axis square
axis off

vp = round(100*[v1 v2 v3 v4 v5 v6 v7 v8]);
disp('thickness vector')
disp(vp)





